version: "3"
services:

  php:
    image: php:8.0.9-fpm
    container_name: php
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./source/laravel:/workspace/example-test-app
      
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  
  mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    # env_file: .env
    env_file: ./mariadb/.env

  redis:
    image: redis
    container_name: redis
    command: redis-server --port 6379
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
